apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  client-passwords: a2Fma2EtcGFzcy0xMjM=
  controller-password: a2Fma2EtcGFzcy00NTY=
  inter-broker-password: a2Fma2EtcGFzcy03ODk=
  system-user-password: a2Fma2EtcGFzcy0xNDc=
